library(ggplot2)
library(tidyverse)
library(MPRAnalyze)

args <- commandArgs(trailingOnly = TRUE)
arg1 <- args[1]

#read in files generated by MPRAflow and turn into matrices
dna_counts <- read.table("dna_counts_padded.csv", header = TRUE, sep=",", row.names=1)
rna_counts <- read.table("rna_counts_padded.csv", header = TRUE, sep=",", row.names=1)
dna_annot <- read.table("dna_annot.tsv", header = TRUE, sep="\t", row.names=1)
rna_annot <- read.table("rna_annot.tsv", header = TRUE, sep="\t", row.names=1)
mycondition <- arg1


#prep for filtering by DNA count of at least 50 per rep
#find columns for rep 1 and rep 2 DNA counts
dna1 <- grep("DNA_HEK293FT_1", colnames(dna_counts))
dna2 <- grep("DNA_HEK293FT_2", colnames(dna_counts))
dna3 <- grep("DNA_HEK293FT_3", colnames(dna_counts))

#calculate sums for rows in the identified columns
sumDNA1 <- rowSums(dna_counts[, dna1])
sumDNA2 <- rowSums(dna_counts[, dna2])
sumDNA3 <- rowSums(dna_counts[, dna3])

#filter rows for bins where DNA sums are greater than or equal to 50
filtered_rows <- (sumDNA1 >= 50) & (sumDNA2 >= 50) & (sumDNA3 >= 50)
filtered_dna_counts <- dna_counts[filtered_rows, ]
filtered_rna_counts <- rna_counts[filtered_rows, ]

#make control matrix by searching for negative scrambled controls
#make vector with controls
#searching for what you named your negative controls, i'm searching for scram because i called them scrambeled#
myControls <- rownames(filtered_dna_counts)[grep("scram", rownames(filtered_dna_counts))]

#assign variable names for myMPRAobject
myDnaCounts <- as.matrix(filtered_dna_counts)
myRnaCounts <- as.matrix(filtered_rna_counts)
myDnaAnnot <- dna_annot
myRnaAnnot <- rna_annot

#crate MPRAobject and estimate depth factors for DNA and RNA libraries
myMPRAobject <- MpraObject(dnaCounts = myDnaCounts, rnaCounts = myRnaCounts, dnaAnnot = myDnaAnnot, rnaAnnot = myRnaAnnot, controls = myControls)

myMPRAobject <- estimateDepthFactors(myMPRAobject, lib.factor = c("replicate", "condition"), which.lib="dna", depth.estimator ="uq")
myMPRAobject <- estimateDepthFactors(myMPRAobject, lib.factor = c("replicate", "condition"), which.lib="rna", depth.estimator ="uq")

#quantification analysis
#find transcription rates
alpha <- getAlpha(myMPRAobject, by.factor = "condition")

write.table(alpha, file="alpha_analysis2.tsv", quote=FALSE, sep='\t', col.names=NA)

png("alpha_boxplot_analysis_prefilt_allcontrols.png", width=800, height=800)
alphabox <- boxplot(alpha)
dev.off()

#changed twosided test to true
res.cond <- testEmpirical(obj = myMPRAobject, statistic = alpha$V1, twoSided=FALSE)
summary(res.cond)
write.table(res.cond, file=paste0("testEmpirical_alpha_", mycondition, "_results_prefilt_allcontrols.tsv"), quote=FALSE, sep='\t', col.names=NA)
res.cond.labeled <- res.cond
res.cond.labeled$label <- row.names(alpha)

write.table(res.cond.labeled, file=paste0("testEmpirical_alpha_", mycondition, "_results_labeled_prefilt_allcontrols.tsv"), quote=FALSE, sep='\t', col.names=NA)

png("all_pval_hist_prefilt_allcontrols.png", width = 800, height = 800)
hist(res.cond$pval.mad, main="all")
dev.off()

png("controls_pval_hist_prefilt_allcontrols.png", width = 800, height = 800)
hist(res.cond$pval.mad[myControls], main="controls")
dev.off()

