symbol TRUE
cache TRUE
offline TRUE
dir_cache /cluster/lab/gcooper/hg38/resources/vep/cache
cache_version 115
assembly GRCh38
fasta /cluster/lab/gcooper/hg38/resources/vep/cache/homo_sapiens/115_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz
#vcf TRUE
check_existing TRUE
hgvs TRUE
plugin CADD,/cluster/lab/gcooper/hg38/resources/cadd_1.7/whole_genome_SNVs.tsv.gz,/cluster/lab/gcooper/hg38/resources/cadd_1.7/gnomad.genomes.r4.0.indel.tsv.gz
fork 4
buffer_size 500000
